version: "2"
services:
  web:
    image: stacks:latest
    ports:
      - "8080:8080"
    expose: 
      - "8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"